VVVVid implementatio (partially)
giorgionegro/server_for_parsing_anime_website pull request #2
Opened 2021-01-16 15:35 UTC by EnricoTirri

2021-01-16 18:40 UTC, giorgionegro requested changes

2021-01-16 18:40 UTC, giorgionegro commented on app.py
> +    with open('../../Desktop/aslatest') as f:
Togli il desktop che e' windows specific o metti una condizione

2021-01-16 18:40 UTC, giorgionegro commented on app.py
> +    driver.close()
Qui ci vuole il quit

2021-01-16 18:40 UTC, giorgionegro commented on app.py
> +    driver = webdriver.Firefox(executable_path='../../Desktop/geckodriver.exe', options=options)
Windows specific

2021-01-16 18:40 UTC, giorgionegro commented on app.py
> +    f = open("../../Desktop/aslatesttemp", "w+")
Windows specific

2021-01-16 18:40 UTC, giorgionegro commented on app.py
> +    driver = webdriver.Firefox(executable_path='../../Desktop/geckodriver.exe', options=options)
Windows specific

2021-01-16 18:44 UTC, EnricoTirri commented
no

Il sab 16 gen 2021, 19:40 giorgionegro <notifications@github.com> ha
scritto:

> *@giorgionegro* requested changes on this pull request.
> ------------------------------
>
> In app.py
> <https://github.com/giorgionegro/server_for_parsing_anime_website/pull/2#discussion_r558998808>
> :
>
> > @@ -197,7 +198,7 @@ def query_as():
>  def latest_as():
>      data = ""
>
> -    with open('aslatest') as f:
> +    with open('../../Desktop/aslatest') as f:
>
> Togli il desktop che e' windows specific o metti una condizione
> ------------------------------
>
> In app.py
> <https://github.com/giorgionegro/server_for_parsing_anime_website/pull/2#discussion_r558998886>
> :
>
> > @@ -145,7 +146,7 @@ def latestepisode_as():
>          img = anime.find_element_by_tag_name("a").find_element_by_tag_name('img').get_attribute('src')
>          data.append([link, title, img])
>      print(data)
> -    driver.quit()
> +    driver.close()
>
> Qui ci vuole il quit
> ------------------------------
>
> In app.py
> <https://github.com/giorgionegro/server_for_parsing_anime_website/pull/2#discussion_r558998931>
> :
>
> > @@ -114,7 +115,7 @@ def latestepisode_as():
>      print('aggiorno latest as')
>      options = Options()
>      options.add_argument("--headless")
> -    driver = webdriver.Firefox(options=options)
> +    driver = webdriver.Firefox(executable_path='../../Desktop/geckodriver.exe', options=options)
>
> Windows specific
> ------------------------------
>
> In app.py
> <https://github.com/giorgionegro/server_for_parsing_anime_website/pull/2#discussion_r558999050>
> :
>
> > @@ -209,7 +210,7 @@ def latestchaceupdate_as():
>          os.remove("aslatesttemp")
>      except:
>          pass
> -    f = open("aslatesttemp", "w+")
> +    f = open("../../Desktop/aslatesttemp", "w+")
>
> Windows specific
> ------------------------------
>
> In app.py
> <https://github.com/giorgionegro/server_for_parsing_anime_website/pull/2#discussion_r558999431>
> :
>
> >      global vidcookie
>      global vidsession_id
>      options = Options()
>      options.add_argument("--headless")
> -    driver = webdriver.Firefox( options=options)
> +    driver = webdriver.Firefox(executable_path='../../Desktop/geckodriver.exe', options=options)
>
> Windows specific
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/giorgionegro/server_for_parsing_anime_website/pull/2#pullrequestreview-569958967>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASPQ6EUM7A4DRQ56PPZJ3OLS2HMSNANCNFSM4WFLAPIQ>
> .
>

2021-01-16 18:46 UTC, EnricoTirri commented on app.py
> +    with open('../../Desktop/aslatest') as f:
fatti i c***i tuoi

2021-01-16 18:48 UTC, EnricoTirri commented on app.py
> +    driver.close()
fattelo te

2021-01-17 14:23 UTC, giorgionegro commented on app.py
> +    global vidCachedSeries
maybe we should consider making the cache in a file

2021-01-17 14:23 UTC, giorgionegro approved these changes

2021-01-17 14:23 UTC, merged